### ISSUE TITLE
Where to create a repository-specific token

### ISSUE THREAD

**Issue by andycox** [atmos/hubot-deploy#42]
The [configuration file docs](https://github.com/atmos/hubot-deploy/blob/master/docs/config-file.md) mention the ability to set a repository-specific token for an application (`github_token`), but I can't seem to find where to create one. 

I assume this is not the same as [personal access tokens](https://github.com/settings/tokens) since I can't limit those to a single repo, nor is it a [developer application](https://github.com/settings/developers), since I don't see where to associate that with a repo. I also couldn't find anything that seemed appropriate in the [OAuth Authorizations API](https://developer.github.com/v3/oauth_authorizations/).

**Comment by atmos** [comment]
@andycox so it's a bit misleading in the sense that it's a token per application you're deploying. This allows you to use different tokens for different apps on different users/organizations. GitHub's API doesn't support repository specific tokens at this point.

**Comment by andycox** [comment]
Makes sense, I think.

I assume that creating a separate machine user is the best way to separate tokens that can access certain repos from a personal account, but machine users are (soon to be) prohibited in my org. Is there any other way to create a token not tied to my personal account that can create deployments through the API?

**Comment by atmos** [comment]
I don't believe so. Machine users are a common pattern due to permissioning in the GitHub API. I think your best bet would be to email support@github.com and describe what you're looking for so they understand the use case better and hopefully roadmap it.

I'm using the `deploy:token:set` [link](https://github.com/atmos/hubot-deploy/blob/master/docs/configuration.md#user-tokens) syntax for my org and the deployments are created by the user instead of a machine user. This handles permissions and correctly attributes the user requesting the deployment in the GitHub API.
